config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :new, :create, :destroy] do
          resources :comments, only: [:new, :create, :destroy]
          resources :likes, only: [:create]
        end
      end 
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', foreign_key: 'author_id'
  has_many :posts, class_name: 'Post', foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end

  def recent_posts
    posts.includes(:author).order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :set_user, only: %i[show update destroy]

  # Get api/v1/users
  def index
    @users = User.all
    render json: @users
  end

  # Get api/v1/users:id
  def show
    render json: @user
  end

  # POST api/v1/users
  def create
    @user = User.new(params)
    if @user.save
      render json: @user, status: :created
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT api/v1/users/:id
  def update
    @user = User.new(params)

    if @user.update(params)
      render json: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # DELETE api/v1/users/:id
  def destroy
    @user.destroy
  end

  private

  # Use callbacks to share common setup or constraints
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_posts
  end
end

app/views/users/index.html.erb
<div class="users">
    <h1> Here is a list of user </h1>
    <ul>
      <% @users.each do |user| %>
        <%= render "shared/user", :user => user %> 
      <% end %>
    </ul>
</div>

app/views/users/show.html.erb
<div class="single_user">
  <%= render "shared/user", user: @user %>
  <div class="bio border-black ">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>

  <div class="posts">
    <% @recent_posts.each do |post| %>
      <%= render "shared/post", post: post %> 
    <% end %>
  </div>

  <button type="button" class="btn">
    <%= link_to "See All Posts", user_posts_path(@user) %>
  </button>

  <button type="button" class="btn"><%= link_to "Create a post", new_user_post_path(@user)  %></button>
</div>