config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :new, :create, :destroy] do
          resources :comments, only: [:new, :create, :destroy]
          resources :likes, only: [:create]
        end
      end 
    end
  end

end

app/views/shared/_comment.html.erb
<% if (post.comments.empty?) %>
  <p>No comment yet.</p>
<% else %>
  <% post.comments.each do |comment| %>
    <ul class="border-black ">
      <li><%= comment.author.name %>: <%= comment.text %></li>
      <% if can? :destroy, comment %>
        <%= button_to "Delete Comment", user_post_comment(user_id: @post.author.id, post_id: @post.id, comment_id: comment.id), method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: @post, url: user_posts_path, class: "form", local: true do |form| %>
    <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="form-group">
        <%= form.label :text %>
        <%= form.text_field :text %>
    </div>
  
    <%= form.submit "Create post" %>
<% end %>

app/views/shared/_post.html.erb
<div class="post">
    <h3> Post'#'<%= post.id %>: <%= post.title %></h3>
    <p><%= truncate(post.text, length: 150, omission: "...") %></p>
    <div class="like-comment">
       Comments : <%= post.comments_counter %>,
       Likes : <%= post.likes_counter %>
    </div>
</div>

app/views/shared/_user.html.erb
<%= link_to user_path(user), class: "user-list-item" do %>
    <li class="list_item border-black ">
      <%= image_tag user.photo %>
      <div class="user_info">
        <h2><%= user.name %></h2>
        <p>Number of posts: <%= user.posts_counter %></p>
      </div>
    </li>
  <% end %>