config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :new, :create, :destroy] do
          resources :comments, only: [:new, :create, :destroy]
          resources :likes, only: [:create]
        end
      end 
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'

  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :set_post, only: %i[show update destroy]

  # GET /api/v1/posts
  def index
    @posts = Post.all
    render json: @posts
  end

  # GET /api/v1/posts/:id
  def show
    render json: @posts
  end

  # POST /api/v1/posts
  def create
    @post = Post.new(post_params)

    if @post.save
      render json: @post, status: :created
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /api/v1/posts
  def update
    if @post.update(post_params)
      render json: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # DELETE /api/v1/posts/:id
  def destroy
    @post.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.order(created_at: :asc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:notice] = 'Post created successfully!'
      redirect_to user_posts_path(current_user)
    else
      flash[:alert] = "Couln't create post!"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path(current_user), notice: 'Post was successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
  
  <div class="posts">
    <%= render partial: "shared/user", locals: { user: @user } %>
    <% @posts.includes(:comments).each do |post| %>
      <%= link_to user_post_path(@user, post), class: "post" do %>
        <%= render "shared/post", post: post %>
        <div class="comments">
          <%= render "shared/comment", post: post %>
        </div>
      <% end %>
    <% end %>
    <button type="button" class="btn">Pagination</button>
  </div>

app/views/posts/new.html.erb
<div class="form-container border-black">
  <h1>New Post</h1>

  <%= render "shared/form", post: @post %>

  <button class="back"><%=link_to 'Back to posts', user_posts_path %></button>
<div>

app/views/posts/show.html.erb
<div class="single-post">
  <div>
  <h2>Post # <%= @post.id %>: <%= @post.title %> by <%= @post.author.name %></h2>
  <p class="post-likes-comments">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
  </div>
  <p> <%= @post.text %></p>

  <div class="comments">
    <%= render "shared/comment", post: @post %>
  </div>

  <div class="like-comment-btn">
      <%= form_with model: @like, url: user_post_likes_path(user_id: @post.author.id, post_id: @post.id), local: true do |form| %>
        <%= form.submit "Add a like", class: "btn" %>
      <% end %>
      <button type="button" class="btn"><%= link_to "Add a comment", new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id)  %></button>
  </div>

  <% if can? :destroy, @post %>
    <%= button_to "Delete", user_post_path(user_id: @post.author.id, post_id: @post.id), method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>

</div>